server:
  port: 2003
spring:
  application:
    name: eureka-consumer-ribbon
eureka:
  client:
    service-url:
       defaultZone: http://localhost:1010/eureka/
#logging:
#  level:
#    root: debug       