spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: COMMUNITY_POLICING
    password: cp
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  level:
    com.kaituo.communitypolicing : debug    