spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: uav
    password: uav
    driver-class-name: oracle.jdbc.driver.OracleDriver 
logging:
  level:
    com.netflix: debug
    